falcon-installer:
  size: 81318072
  sha: sha256:fb5373d373dc30c1f6f07e02f505c0384772a063b75cf5dfa417f15f5db21e60
falcon-installer.exe:
  size: 83249152
  sha: sha256:2fb1d3e6a45c402fb1d4449278d6336c8e080b1b008d210f374da040eea29e65
